# Generated by Django 4.1.1 on 2022-09-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('industry', models.CharField(max_length=100)),
                ('employees_count', models.IntegerField()),
                ('sic_no', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('exchange_id', models.IntegerField()),
                ('cik_no', models.CharField(max_length=100)),
                ('cusip', models.CharField(max_length=100)),
                ('currency_id', models.CharField(max_length=100)),
                ('data_source_id', models.CharField(max_length=100)),
                ('ckr_log', models.CharField(max_length=100)),
                ('similar_fund_log', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('is_active', models.CharField(max_length=100)),
                ('url_slug', models.CharField(max_length=100)),
                ('delisted_date', models.DateField()),
                ('delisted_reason', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=100)),
                ('image_aspect_ratio', models.CharField(max_length=100)),
                ('cumulative_return_update', models.CharField(max_length=100)),
            ],
        ),
    ]
