# Generated by Django 4.1.1 on 2022-09-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_series', '0002_equities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equities',
            name='image_aspect_ratio',
            field=models.FloatField(),
        ),
    ]
